/* tslint:disable */
/* eslint-disable */
/**
 * Halo Next API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios'
import { Configuration } from '../configuration'
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from '../common'
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base'
// @ts-ignore
import { Comment } from '../models'
// @ts-ignore
import { CommentRequest } from '../models'
// @ts-ignore
import { ListedCommentList } from '../models'
// @ts-ignore
import { Reply } from '../models'
// @ts-ignore
import { ReplyRequest } from '../models'
/**
 * ApiHaloRunV1alpha1CommentApi - axios parameter creator
 * @export
 */
export const ApiHaloRunV1alpha1CommentApiAxiosParamCreator = function (configuration?: Configuration) {
  return {
    /**
     * Create a comment.
     * @param {CommentRequest} commentRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createComment: async (commentRequest: CommentRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
      // verify required parameter 'commentRequest' is not null or undefined
      assertParamExists('createComment', 'commentRequest', commentRequest)
      const localVarPath = `/apis/api.halo.run/v1alpha1/comments`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication BasicAuth required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration)

      // authentication BearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      localVarHeaderParameter['Content-Type'] = 'application/json'

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }
      localVarRequestOptions.data = serializeDataIfNeeded(commentRequest, localVarRequestOptions, configuration)

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * Create a reply.
     * @param {string} name
     * @param {ReplyRequest} replyRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createReply: async (
      name: string,
      replyRequest: ReplyRequest,
      options: AxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'name' is not null or undefined
      assertParamExists('createReply', 'name', name)
      // verify required parameter 'replyRequest' is not null or undefined
      assertParamExists('createReply', 'replyRequest', replyRequest)
      const localVarPath = `/apis/api.halo.run/v1alpha1/comments/{name}/reply`.replace(
        `{${'name'}}`,
        encodeURIComponent(String(name)),
      )
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication BasicAuth required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration)

      // authentication BearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      localVarHeaderParameter['Content-Type'] = 'application/json'

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }
      localVarRequestOptions.data = serializeDataIfNeeded(replyRequest, localVarRequestOptions, configuration)

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     * List comments.
     * @param {'LAST_REPLY_TIME' | 'REPLY_COUNT' | 'CREATE_TIME'} [sort] Comment collation.
     * @param {string} [keyword] Comments filtered by keyword.
     * @param {boolean} [hidden] The comment is hidden from the theme side.
     * @param {boolean} [top] Comment top display.
     * @param {boolean} [sortOrder] ascending order If it is true; otherwise, it is in descending order.
     * @param {boolean} [approved] Comments approved.
     * @param {boolean} [allowNotification] Send notifications when there are new replies.
     * @param {string} [ownerKind] Commenter kind.
     * @param {string} [ownerName] Commenter name.
     * @param {string} [subjectKind] Comment subject kind.
     * @param {string} [subjectName] Comment subject name.
     * @param {number} [size] Size of one page. Zero indicates no limit.
     * @param {number} [page] The page number. Zero indicates no page.
     * @param {Array<string>} [labelSelector] Label selector for filtering.
     * @param {Array<string>} [fieldSelector] Field selector for filtering.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listComments: async (
      sort?: 'LAST_REPLY_TIME' | 'REPLY_COUNT' | 'CREATE_TIME',
      keyword?: string,
      hidden?: boolean,
      top?: boolean,
      sortOrder?: boolean,
      approved?: boolean,
      allowNotification?: boolean,
      ownerKind?: string,
      ownerName?: string,
      subjectKind?: string,
      subjectName?: string,
      size?: number,
      page?: number,
      labelSelector?: Array<string>,
      fieldSelector?: Array<string>,
      options: AxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      const localVarPath = `/apis/api.halo.run/v1alpha1/comments`
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }

      const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication BasicAuth required
      // http basic authentication required
      setBasicAuthToObject(localVarRequestOptions, configuration)

      // authentication BearerAuth required
      // http bearer authentication required
      await setBearerAuthToObject(localVarHeaderParameter, configuration)

      if (sort !== undefined) {
        localVarQueryParameter['sort'] = sort
      }

      if (keyword !== undefined) {
        localVarQueryParameter['keyword'] = keyword
      }

      if (hidden !== undefined) {
        localVarQueryParameter['hidden'] = hidden
      }

      if (top !== undefined) {
        localVarQueryParameter['top'] = top
      }

      if (sortOrder !== undefined) {
        localVarQueryParameter['sortOrder'] = sortOrder
      }

      if (approved !== undefined) {
        localVarQueryParameter['approved'] = approved
      }

      if (allowNotification !== undefined) {
        localVarQueryParameter['allowNotification'] = allowNotification
      }

      if (ownerKind !== undefined) {
        localVarQueryParameter['ownerKind'] = ownerKind
      }

      if (ownerName !== undefined) {
        localVarQueryParameter['ownerName'] = ownerName
      }

      if (subjectKind !== undefined) {
        localVarQueryParameter['subjectKind'] = subjectKind
      }

      if (subjectName !== undefined) {
        localVarQueryParameter['subjectName'] = subjectName
      }

      if (size !== undefined) {
        localVarQueryParameter['size'] = size
      }

      if (page !== undefined) {
        localVarQueryParameter['page'] = page
      }

      if (labelSelector) {
        localVarQueryParameter['labelSelector'] = labelSelector
      }

      if (fieldSelector) {
        localVarQueryParameter['fieldSelector'] = fieldSelector
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter)
      let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = { ...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers }

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
  }
}

/**
 * ApiHaloRunV1alpha1CommentApi - functional programming interface
 * @export
 */
export const ApiHaloRunV1alpha1CommentApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = ApiHaloRunV1alpha1CommentApiAxiosParamCreator(configuration)
  return {
    /**
     * Create a comment.
     * @param {CommentRequest} commentRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async createComment(
      commentRequest: CommentRequest,
      options?: AxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Comment>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.createComment(commentRequest, options)
      return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)
    },
    /**
     * Create a reply.
     * @param {string} name
     * @param {ReplyRequest} replyRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async createReply(
      name: string,
      replyRequest: ReplyRequest,
      options?: AxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Reply>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.createReply(name, replyRequest, options)
      return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)
    },
    /**
     * List comments.
     * @param {'LAST_REPLY_TIME' | 'REPLY_COUNT' | 'CREATE_TIME'} [sort] Comment collation.
     * @param {string} [keyword] Comments filtered by keyword.
     * @param {boolean} [hidden] The comment is hidden from the theme side.
     * @param {boolean} [top] Comment top display.
     * @param {boolean} [sortOrder] ascending order If it is true; otherwise, it is in descending order.
     * @param {boolean} [approved] Comments approved.
     * @param {boolean} [allowNotification] Send notifications when there are new replies.
     * @param {string} [ownerKind] Commenter kind.
     * @param {string} [ownerName] Commenter name.
     * @param {string} [subjectKind] Comment subject kind.
     * @param {string} [subjectName] Comment subject name.
     * @param {number} [size] Size of one page. Zero indicates no limit.
     * @param {number} [page] The page number. Zero indicates no page.
     * @param {Array<string>} [labelSelector] Label selector for filtering.
     * @param {Array<string>} [fieldSelector] Field selector for filtering.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async listComments(
      sort?: 'LAST_REPLY_TIME' | 'REPLY_COUNT' | 'CREATE_TIME',
      keyword?: string,
      hidden?: boolean,
      top?: boolean,
      sortOrder?: boolean,
      approved?: boolean,
      allowNotification?: boolean,
      ownerKind?: string,
      ownerName?: string,
      subjectKind?: string,
      subjectName?: string,
      size?: number,
      page?: number,
      labelSelector?: Array<string>,
      fieldSelector?: Array<string>,
      options?: AxiosRequestConfig,
    ): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListedCommentList>> {
      const localVarAxiosArgs = await localVarAxiosParamCreator.listComments(
        sort,
        keyword,
        hidden,
        top,
        sortOrder,
        approved,
        allowNotification,
        ownerKind,
        ownerName,
        subjectKind,
        subjectName,
        size,
        page,
        labelSelector,
        fieldSelector,
        options,
      )
      return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)
    },
  }
}

/**
 * ApiHaloRunV1alpha1CommentApi - factory interface
 * @export
 */
export const ApiHaloRunV1alpha1CommentApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = ApiHaloRunV1alpha1CommentApiFp(configuration)
  return {
    /**
     * Create a comment.
     * @param {CommentRequest} commentRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createComment(commentRequest: CommentRequest, options?: any): AxiosPromise<Comment> {
      return localVarFp.createComment(commentRequest, options).then((request) => request(axios, basePath))
    },
    /**
     * Create a reply.
     * @param {string} name
     * @param {ReplyRequest} replyRequest
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createReply(name: string, replyRequest: ReplyRequest, options?: any): AxiosPromise<Reply> {
      return localVarFp.createReply(name, replyRequest, options).then((request) => request(axios, basePath))
    },
    /**
     * List comments.
     * @param {'LAST_REPLY_TIME' | 'REPLY_COUNT' | 'CREATE_TIME'} [sort] Comment collation.
     * @param {string} [keyword] Comments filtered by keyword.
     * @param {boolean} [hidden] The comment is hidden from the theme side.
     * @param {boolean} [top] Comment top display.
     * @param {boolean} [sortOrder] ascending order If it is true; otherwise, it is in descending order.
     * @param {boolean} [approved] Comments approved.
     * @param {boolean} [allowNotification] Send notifications when there are new replies.
     * @param {string} [ownerKind] Commenter kind.
     * @param {string} [ownerName] Commenter name.
     * @param {string} [subjectKind] Comment subject kind.
     * @param {string} [subjectName] Comment subject name.
     * @param {number} [size] Size of one page. Zero indicates no limit.
     * @param {number} [page] The page number. Zero indicates no page.
     * @param {Array<string>} [labelSelector] Label selector for filtering.
     * @param {Array<string>} [fieldSelector] Field selector for filtering.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listComments(
      sort?: 'LAST_REPLY_TIME' | 'REPLY_COUNT' | 'CREATE_TIME',
      keyword?: string,
      hidden?: boolean,
      top?: boolean,
      sortOrder?: boolean,
      approved?: boolean,
      allowNotification?: boolean,
      ownerKind?: string,
      ownerName?: string,
      subjectKind?: string,
      subjectName?: string,
      size?: number,
      page?: number,
      labelSelector?: Array<string>,
      fieldSelector?: Array<string>,
      options?: any,
    ): AxiosPromise<ListedCommentList> {
      return localVarFp
        .listComments(
          sort,
          keyword,
          hidden,
          top,
          sortOrder,
          approved,
          allowNotification,
          ownerKind,
          ownerName,
          subjectKind,
          subjectName,
          size,
          page,
          labelSelector,
          fieldSelector,
          options,
        )
        .then((request) => request(axios, basePath))
    },
  }
}

/**
 * Request parameters for createComment operation in ApiHaloRunV1alpha1CommentApi.
 * @export
 * @interface ApiHaloRunV1alpha1CommentApiCreateCommentRequest
 */
export interface ApiHaloRunV1alpha1CommentApiCreateCommentRequest {
  /**
   *
   * @type {CommentRequest}
   * @memberof ApiHaloRunV1alpha1CommentApiCreateComment
   */
  readonly commentRequest: CommentRequest
}

/**
 * Request parameters for createReply operation in ApiHaloRunV1alpha1CommentApi.
 * @export
 * @interface ApiHaloRunV1alpha1CommentApiCreateReplyRequest
 */
export interface ApiHaloRunV1alpha1CommentApiCreateReplyRequest {
  /**
   *
   * @type {string}
   * @memberof ApiHaloRunV1alpha1CommentApiCreateReply
   */
  readonly name: string

  /**
   *
   * @type {ReplyRequest}
   * @memberof ApiHaloRunV1alpha1CommentApiCreateReply
   */
  readonly replyRequest: ReplyRequest
}

/**
 * Request parameters for listComments operation in ApiHaloRunV1alpha1CommentApi.
 * @export
 * @interface ApiHaloRunV1alpha1CommentApiListCommentsRequest
 */
export interface ApiHaloRunV1alpha1CommentApiListCommentsRequest {
  /**
   * Comment collation.
   * @type {'LAST_REPLY_TIME' | 'REPLY_COUNT' | 'CREATE_TIME'}
   * @memberof ApiHaloRunV1alpha1CommentApiListComments
   */
  readonly sort?: 'LAST_REPLY_TIME' | 'REPLY_COUNT' | 'CREATE_TIME'

  /**
   * Comments filtered by keyword.
   * @type {string}
   * @memberof ApiHaloRunV1alpha1CommentApiListComments
   */
  readonly keyword?: string

  /**
   * The comment is hidden from the theme side.
   * @type {boolean}
   * @memberof ApiHaloRunV1alpha1CommentApiListComments
   */
  readonly hidden?: boolean

  /**
   * Comment top display.
   * @type {boolean}
   * @memberof ApiHaloRunV1alpha1CommentApiListComments
   */
  readonly top?: boolean

  /**
   * ascending order If it is true; otherwise, it is in descending order.
   * @type {boolean}
   * @memberof ApiHaloRunV1alpha1CommentApiListComments
   */
  readonly sortOrder?: boolean

  /**
   * Comments approved.
   * @type {boolean}
   * @memberof ApiHaloRunV1alpha1CommentApiListComments
   */
  readonly approved?: boolean

  /**
   * Send notifications when there are new replies.
   * @type {boolean}
   * @memberof ApiHaloRunV1alpha1CommentApiListComments
   */
  readonly allowNotification?: boolean

  /**
   * Commenter kind.
   * @type {string}
   * @memberof ApiHaloRunV1alpha1CommentApiListComments
   */
  readonly ownerKind?: string

  /**
   * Commenter name.
   * @type {string}
   * @memberof ApiHaloRunV1alpha1CommentApiListComments
   */
  readonly ownerName?: string

  /**
   * Comment subject kind.
   * @type {string}
   * @memberof ApiHaloRunV1alpha1CommentApiListComments
   */
  readonly subjectKind?: string

  /**
   * Comment subject name.
   * @type {string}
   * @memberof ApiHaloRunV1alpha1CommentApiListComments
   */
  readonly subjectName?: string

  /**
   * Size of one page. Zero indicates no limit.
   * @type {number}
   * @memberof ApiHaloRunV1alpha1CommentApiListComments
   */
  readonly size?: number

  /**
   * The page number. Zero indicates no page.
   * @type {number}
   * @memberof ApiHaloRunV1alpha1CommentApiListComments
   */
  readonly page?: number

  /**
   * Label selector for filtering.
   * @type {Array<string>}
   * @memberof ApiHaloRunV1alpha1CommentApiListComments
   */
  readonly labelSelector?: Array<string>

  /**
   * Field selector for filtering.
   * @type {Array<string>}
   * @memberof ApiHaloRunV1alpha1CommentApiListComments
   */
  readonly fieldSelector?: Array<string>
}

/**
 * ApiHaloRunV1alpha1CommentApi - object-oriented interface
 * @export
 * @class ApiHaloRunV1alpha1CommentApi
 * @extends {BaseAPI}
 */
export class ApiHaloRunV1alpha1CommentApi extends BaseAPI {
  /**
   * Create a comment.
   * @param {ApiHaloRunV1alpha1CommentApiCreateCommentRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ApiHaloRunV1alpha1CommentApi
   */
  public createComment(
    requestParameters: ApiHaloRunV1alpha1CommentApiCreateCommentRequest,
    options?: AxiosRequestConfig,
  ) {
    return ApiHaloRunV1alpha1CommentApiFp(this.configuration)
      .createComment(requestParameters.commentRequest, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   * Create a reply.
   * @param {ApiHaloRunV1alpha1CommentApiCreateReplyRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ApiHaloRunV1alpha1CommentApi
   */
  public createReply(requestParameters: ApiHaloRunV1alpha1CommentApiCreateReplyRequest, options?: AxiosRequestConfig) {
    return ApiHaloRunV1alpha1CommentApiFp(this.configuration)
      .createReply(requestParameters.name, requestParameters.replyRequest, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   * List comments.
   * @param {ApiHaloRunV1alpha1CommentApiListCommentsRequest} requestParameters Request parameters.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ApiHaloRunV1alpha1CommentApi
   */
  public listComments(
    requestParameters: ApiHaloRunV1alpha1CommentApiListCommentsRequest = {},
    options?: AxiosRequestConfig,
  ) {
    return ApiHaloRunV1alpha1CommentApiFp(this.configuration)
      .listComments(
        requestParameters.sort,
        requestParameters.keyword,
        requestParameters.hidden,
        requestParameters.top,
        requestParameters.sortOrder,
        requestParameters.approved,
        requestParameters.allowNotification,
        requestParameters.ownerKind,
        requestParameters.ownerName,
        requestParameters.subjectKind,
        requestParameters.subjectName,
        requestParameters.size,
        requestParameters.page,
        requestParameters.labelSelector,
        requestParameters.fieldSelector,
        options,
      )
      .then((request) => request(this.axios, this.basePath))
  }
}
