/* tslint:disable */
/* eslint-disable */
/**
 * Halo Next API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Ref } from './ref'

/**
 *
 * @export
 * @interface AttachmentSpec
 */
export interface AttachmentSpec {
  /**
   * Display name of attachment
   * @type {string}
   * @memberof AttachmentSpec
   */
  displayName?: string
  /**
   *
   * @type {Ref}
   * @memberof AttachmentSpec
   */
  groupRef?: Ref
  /**
   *
   * @type {Ref}
   * @memberof AttachmentSpec
   */
  policyRef?: Ref
  /**
   *
   * @type {Ref}
   * @memberof AttachmentSpec
   */
  uploadedBy?: Ref
  /**
   * Media type of attachment
   * @type {string}
   * @memberof AttachmentSpec
   */
  mediaType?: string
  /**
   * Size of attachment. Unit is Byte
   * @type {number}
   * @memberof AttachmentSpec
   */
  size?: number
  /**
   * Tags of attachment
   * @type {Array<string>}
   * @memberof AttachmentSpec
   */
  tags?: Array<string>
}
