/* tslint:disable */
/* eslint-disable */
/**
 * Halo Next API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CompactPost } from './compact-post'

/**
 *
 * @export
 * @interface CategoryStatus
 */
export interface CategoryStatus {
  /**
   *
   * @type {string}
   * @memberof CategoryStatus
   */
  permalink?: string
  /**
   *
   * @type {Array<CompactPost>}
   * @memberof CategoryStatus
   */
  posts?: Array<CompactPost>
}
