/* tslint:disable */
/* eslint-disable */
/**
 * Halo Next API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CommentSpec } from './comment-spec'
import { CommentStatus } from './comment-status'
import { Metadata } from './metadata'
import { OwnerInfo } from './owner-info'

/**
 * A chunk of items.
 * @export
 * @interface CommentVo
 */
export interface CommentVo {
  /**
   *
   * @type {Metadata}
   * @memberof CommentVo
   */
  metadata: Metadata
  /**
   *
   * @type {CommentSpec}
   * @memberof CommentVo
   */
  spec: CommentSpec
  /**
   *
   * @type {CommentStatus}
   * @memberof CommentVo
   */
  status?: CommentStatus
  /**
   *
   * @type {OwnerInfo}
   * @memberof CommentVo
   */
  owner: OwnerInfo
}
