/* tslint:disable */
/* eslint-disable */
/**
 * Halo Next API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface CommentSubjectRef
 */
export interface CommentSubjectRef {
  /**
   *
   * @type {string}
   * @memberof CommentSubjectRef
   */
  kind: string
  /**
   *
   * @type {string}
   * @memberof CommentSubjectRef
   */
  name: string
}
