/* tslint:disable */
/* eslint-disable */
/**
 * Halo Next API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface CompactPost
 */
export interface CompactPost {
  /**
   *
   * @type {string}
   * @memberof CompactPost
   */
  name?: string
  /**
   *
   * @type {string}
   * @memberof CompactPost
   */
  visible?: CompactPostVisibleEnum
  /**
   *
   * @type {boolean}
   * @memberof CompactPost
   */
  published?: boolean
}

export const CompactPostVisibleEnum = {
  Public: 'PUBLIC',
  Internal: 'INTERNAL',
  Private: 'PRIVATE',
} as const

export type CompactPostVisibleEnum = typeof CompactPostVisibleEnum[keyof typeof CompactPostVisibleEnum]
