/* tslint:disable */
/* eslint-disable */
/**
 * Halo Next API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Ref } from './ref'

/**
 *
 * @export
 * @interface ContentRequest
 */
export interface ContentRequest {
  /**
   *
   * @type {Ref}
   * @memberof ContentRequest
   */
  subjectRef: Ref
  /**
   *
   * @type {string}
   * @memberof ContentRequest
   */
  headSnapshotName?: string
  /**
   *
   * @type {string}
   * @memberof ContentRequest
   */
  raw: string
  /**
   *
   * @type {string}
   * @memberof ContentRequest
   */
  content: string
  /**
   *
   * @type {string}
   * @memberof ContentRequest
   */
  rawType: string
}
