/* tslint:disable */
/* eslint-disable */
/**
 * Halo Next API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LinkGroupSpec } from './link-group-spec'
import { Metadata } from './metadata'

/**
 *
 * @export
 * @interface LinkGroup
 */
export interface LinkGroup {
  /**
   *
   * @type {LinkGroupSpec}
   * @memberof LinkGroup
   */
  spec?: LinkGroupSpec
  /**
   *
   * @type {string}
   * @memberof LinkGroup
   */
  apiVersion: string
  /**
   *
   * @type {string}
   * @memberof LinkGroup
   */
  kind: string
  /**
   *
   * @type {Metadata}
   * @memberof LinkGroup
   */
  metadata: Metadata
}
