/* tslint:disable */
/* eslint-disable */
/**
 * Halo Next API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface LinkGroupSpec
 */
export interface LinkGroupSpec {
  /**
   *
   * @type {string}
   * @memberof LinkGroupSpec
   */
  displayName: string
  /**
   *
   * @type {number}
   * @memberof LinkGroupSpec
   */
  priority?: number
  /**
   * Names of links below this group.
   * @type {Array<string>}
   * @memberof LinkGroupSpec
   */
  links?: Array<string>
}
