/* tslint:disable */
/* eslint-disable */
/**
 * Halo Next API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { OwnerInfo } from './owner-info'
import { Reply } from './reply'

/**
 * A chunk of items.
 * @export
 * @interface ListedReply
 */
export interface ListedReply {
  /**
   *
   * @type {Reply}
   * @memberof ListedReply
   */
  reply: Reply
  /**
   *
   * @type {OwnerInfo}
   * @memberof ListedReply
   */
  owner: OwnerInfo
}
