/* tslint:disable */
/* eslint-disable */
/**
 * Halo Next API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Category } from './category'
import { Contributor } from './contributor'
import { Post } from './post'
import { Stats } from './stats'
import { Tag } from './tag'

/**
 * A chunk of items.
 * @export
 * @interface ListedPost
 */
export interface ListedPost {
  /**
   *
   * @type {Post}
   * @memberof ListedPost
   */
  post: Post
  /**
   *
   * @type {Array<Category>}
   * @memberof ListedPost
   */
  categories: Array<Category>
  /**
   *
   * @type {Array<Tag>}
   * @memberof ListedPost
   */
  tags: Array<Tag>
  /**
   *
   * @type {Array<Contributor>}
   * @memberof ListedPost
   */
  contributors: Array<Contributor>
  /**
   *
   * @type {Contributor}
   * @memberof ListedPost
   */
  owner: Contributor
  /**
   *
   * @type {Stats}
   * @memberof ListedPost
   */
  stats: Stats
}
