/* tslint:disable */
/* eslint-disable */
/**
 * Halo Next API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MenuSpec } from './menu-spec'
import { Metadata } from './metadata'

/**
 *
 * @export
 * @interface Menu
 */
export interface Menu {
  /**
   *
   * @type {MenuSpec}
   * @memberof Menu
   */
  spec: MenuSpec
  /**
   *
   * @type {string}
   * @memberof Menu
   */
  apiVersion: string
  /**
   *
   * @type {string}
   * @memberof Menu
   */
  kind: string
  /**
   *
   * @type {Metadata}
   * @memberof Menu
   */
  metadata: Metadata
}
