/* tslint:disable */
/* eslint-disable */
/**
 * Halo Next API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Metadata } from './metadata'
import { PluginSpec } from './plugin-spec'
import { PluginStatus } from './plugin-status'

/**
 *
 * @export
 * @interface Plugin
 */
export interface Plugin {
  /**
   *
   * @type {PluginSpec}
   * @memberof Plugin
   */
  spec: PluginSpec
  /**
   *
   * @type {PluginStatus}
   * @memberof Plugin
   */
  status?: PluginStatus
  /**
   *
   * @type {string}
   * @memberof Plugin
   */
  apiVersion: string
  /**
   *
   * @type {string}
   * @memberof Plugin
   */
  kind: string
  /**
   *
   * @type {Metadata}
   * @memberof Plugin
   */
  metadata: Metadata
}
