/* tslint:disable */
/* eslint-disable */
/**
 * Halo Next API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Metadata } from './metadata'
import { ReplySpec } from './reply-spec'

/**
 *
 * @export
 * @interface Reply
 */
export interface Reply {
  /**
   *
   * @type {ReplySpec}
   * @memberof Reply
   */
  spec: ReplySpec
  /**
   *
   * @type {string}
   * @memberof Reply
   */
  apiVersion: string
  /**
   *
   * @type {string}
   * @memberof Reply
   */
  kind: string
  /**
   *
   * @type {Metadata}
   * @memberof Reply
   */
  metadata: Metadata
}
