/* tslint:disable */
/* eslint-disable */
/**
 * Halo Next API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface SettingSpec
 */
export interface SettingSpec {
  /**
   *
   * @type {string}
   * @memberof SettingSpec
   */
  group: string
  /**
   *
   * @type {string}
   * @memberof SettingSpec
   */
  label?: string
  /**
   *
   * @type {Array<object>}
   * @memberof SettingSpec
   */
  formSchema?: Array<object>
}
