/* tslint:disable */
/* eslint-disable */
/**
 * Halo Next API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Metadata } from './metadata'
import { SinglePageSpec } from './single-page-spec'
import { SinglePageStatus } from './single-page-status'

/**
 *
 * @export
 * @interface SinglePage
 */
export interface SinglePage {
  /**
   *
   * @type {SinglePageSpec}
   * @memberof SinglePage
   */
  spec: SinglePageSpec
  /**
   *
   * @type {SinglePageStatus}
   * @memberof SinglePage
   */
  status?: SinglePageStatus
  /**
   *
   * @type {string}
   * @memberof SinglePage
   */
  apiVersion: string
  /**
   *
   * @type {string}
   * @memberof SinglePage
   */
  kind: string
  /**
   *
   * @type {Metadata}
   * @memberof SinglePage
   */
  metadata: Metadata
}
