/* tslint:disable */
/* eslint-disable */
/**
 * Halo Next API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Stats
 */
export interface Stats {
  /**
   *
   * @type {number}
   * @memberof Stats
   */
  visits?: number
  /**
   *
   * @type {number}
   * @memberof Stats
   */
  comments?: number
  /**
   *
   * @type {number}
   * @memberof Stats
   */
  approvedComments?: number
  /**
   *
   * @type {number}
   * @memberof Stats
   */
  upvotes?: number
  /**
   *
   * @type {number}
   * @memberof Stats
   */
  users?: number
  /**
   *
   * @type {number}
   * @memberof Stats
   */
  posts?: number
}
