/* tslint:disable */
/* eslint-disable */
/**
 * Halo Next API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Metadata } from './metadata'
import { TagSpec } from './tag-spec'
import { TagStatus } from './tag-status'

/**
 *
 * @export
 * @interface Tag
 */
export interface Tag {
  /**
   *
   * @type {TagSpec}
   * @memberof Tag
   */
  spec: TagSpec
  /**
   *
   * @type {TagStatus}
   * @memberof Tag
   */
  status?: TagStatus
  /**
   *
   * @type {string}
   * @memberof Tag
   */
  apiVersion: string
  /**
   *
   * @type {string}
   * @memberof Tag
   */
  kind: string
  /**
   *
   * @type {Metadata}
   * @memberof Tag
   */
  metadata: Metadata
}
