/* tslint:disable */
/* eslint-disable */
/**
 * Halo Next API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Author } from './author'
import { CustomTemplates } from './custom-templates'

/**
 *
 * @export
 * @interface ThemeSpec
 */
export interface ThemeSpec {
  /**
   *
   * @type {string}
   * @memberof ThemeSpec
   */
  displayName: string
  /**
   *
   * @type {Author}
   * @memberof ThemeSpec
   */
  author: Author
  /**
   *
   * @type {string}
   * @memberof ThemeSpec
   */
  description?: string
  /**
   *
   * @type {string}
   * @memberof ThemeSpec
   */
  logo?: string
  /**
   *
   * @type {string}
   * @memberof ThemeSpec
   */
  website?: string
  /**
   *
   * @type {string}
   * @memberof ThemeSpec
   */
  repo?: string
  /**
   *
   * @type {string}
   * @memberof ThemeSpec
   */
  version: string
  /**
   *
   * @type {string}
   * @memberof ThemeSpec
   */
  require: string
  /**
   *
   * @type {string}
   * @memberof ThemeSpec
   */
  settingName?: string
  /**
   *
   * @type {string}
   * @memberof ThemeSpec
   */
  configMapName?: string
  /**
   *
   * @type {CustomTemplates}
   * @memberof ThemeSpec
   */
  customTemplates?: CustomTemplates
}
